const jobCategories = [
  'Accounting and Finance',
  'Administrative',
  'Advertising and Marketing',
  'Architecture and Engineering',
  'Art, Fashion, and Design',
  'Banking and Financial Services',
  'Beauty and Wellness',
  'Business Operations',
  'Community and Social Services',
  'Construction and Facilities',
  'Consulting',
  'Customer Service',
  'Education and Training',
  'Energy and Utilities',
  'Engineering',
  'Entertainment and Media',
  'Food and Beverage',
  'Government and Public Administration',
  'Healthcare',
  'Hospitality and Tourism',
  'Human Resources',
  'Information Technology',
  'Insurance',
  'Legal',
  'Logistics and Transportation',
  'Maintenance and Repair',
  'Management',
  'Manufacturing and Production',
  'Military and Protective Services',
  'Nonprofit',
  'Personal Care and Service',
  'Product Management',
  'Program and Project Management',
  'Quality Assurance and Safety',
  'Real Estate',
  'Research and Development',
  'Sales',
  'Science',
  'Sports and Recreation',
  'Support',
  'Writing and Content',
]

export default jobCategories
